FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm ci
CMD ["sh", "-c", "npx prisma db push && npx tsx prisma/seed.ts"]
